name: Run Tests
on:
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      environment:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.6.8'

      - name: Setup Python virtual environment
        run: python -m venv python3-virtualenv

      - name: Install dependencies
        run: python3-virtualenv/bin/pip install -r requirements.txt

      - name: Run tests
        run: ./run_test.sh

      - name: Send Discord message on failure
        if: ${{ failure() && inputs.environment == 'production' }}
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=⚠️ Deployment Tests Failed"
